// Code generated by MockGen. DO NOT EDIT.
// Source: src/cartesian/configs/config.go

// Package mock_configs is a generated GoMock package.
package mock_configs

import (
	gomock "github.com/golang/mock/gomock"
)

// MockEntityTemplate is a mock of EntityTemplate interface
type MockEntityTemplate struct {
	ctrl     *gomock.Controller
	recorder *MockEntityTemplateMockRecorder
}

// MockEntityTemplateMockRecorder is the mock recorder for MockEntityTemplate
type MockEntityTemplateMockRecorder struct {
	mock *MockEntityTemplate
}

// NewMockEntityTemplate creates a new mock instance
func NewMockEntityTemplate(ctrl *gomock.Controller) *MockEntityTemplate {
	mock := &MockEntityTemplate{ctrl: ctrl}
	mock.recorder = &MockEntityTemplateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockEntityTemplate) EXPECT() *MockEntityTemplateMockRecorder {
	return m.recorder
}
