// Code generated by MockGen. DO NOT EDIT.
// Source: src/cartesian/config/io.go

// Package mock_config is a generated GoMock package.
package mock_config

import (
	gomock "github.com/golang/mock/gomock"
	abstract "github.com/zored/cartesian/src/cartesian/abstract"
	config "github.com/zored/cartesian/src/cartesian/configs"
	reflect "reflect"
)

// MockIO is a mock of IO interface
type MockIO struct {
	ctrl     *gomock.Controller
	recorder *MockIOMockRecorder
}

// MockIOMockRecorder is the mock recorder for MockIO
type MockIOMockRecorder struct {
	mock *MockIO
}

// NewMockIO creates a new mock instance
func NewMockIO(ctrl *gomock.Controller) *MockIO {
	mock := &MockIO{ctrl: ctrl}
	mock.recorder = &MockIOMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIO) EXPECT() *MockIOMockRecorder {
	return m.recorder
}

// GetInput mocks base method
func (m *MockIO) GetInput() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInput")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// GetInput indicates an expected call of GetInput
func (mr *MockIOMockRecorder) GetInput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInput", reflect.TypeOf((*MockIO)(nil).GetInput))
}

// GetOutput mocks base method
func (m *MockIO) GetOutput() abstract.Entities {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutput")
	ret0, _ := ret[0].(abstract.Entities)
	return ret0
}

// GetOutput indicates an expected call of GetOutput
func (mr *MockIOMockRecorder) GetOutput() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutput", reflect.TypeOf((*MockIO)(nil).GetOutput))
}

// SetOutput mocks base method
func (m *MockIO) SetOutput(arg0 abstract.Entities) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutput", arg0)
}

// SetOutput indicates an expected call of SetOutput
func (mr *MockIOMockRecorder) SetOutput(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutput", reflect.TypeOf((*MockIO)(nil).SetOutput), arg0)
}

// SetParentIO mocks base method
func (m *MockIO) SetParentIO(arg0 config.IO) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetParentIO", arg0)
}

// SetParentIO indicates an expected call of SetParentIO
func (mr *MockIOMockRecorder) SetParentIO(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetParentIO", reflect.TypeOf((*MockIO)(nil).SetParentIO), arg0)
}
